# Generated by Django 5.1.5 on 2025-02-22 19:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0003_alter_usuario_first_name_alter_usuario_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('analista', 'Analista'), ('cliente', 'Cliente')], default='cliente', max_length=20, verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='first_name',
            field=models.CharField(default='Desconocido', max_length=255, verbose_name='Nombres'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='last_name',
            field=models.CharField(default='Desconocido', max_length=255, verbose_name='Apellidos'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_username', message='La cédula debe contener solo números', regex='^\\d+$')], verbose_name='Cédula'),
        ),
    ]
