# Generated by Django 5.1.5 on 2025-03-15 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0005_usuario_tipo_cedula'),
    ]

    operations = [
        migrations.AddField(
            model_name='reembolso',
            name='cedula_paciente',
            field=models.ImageField(default=1, upload_to='photos/reembolso/'),
            preserve_default=False,
        ),
    ]
