# Generated by Django 5.1.5 on 2025-03-15 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0006_reembolso_cedula_paciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reembolso',
            name='cedula_paciente',
            field=models.FileField(upload_to='pdfs/reembolso/'),
        ),
        migrations.AlterField(
            model_name='reembolso',
            name='informe_ampliado',
            field=models.FileField(upload_to='pdfs/reembolso/'),
        ),
        migrations.AlterField(
            model_name='reembolso',
            name='informe_resultado',
            field=models.FileField(upload_to='pdfs/reembolso/'),
        ),
    ]
