# Generated by Django 5.1.5 on 2025-03-15 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0007_alter_reembolso_cedula_paciente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reembolso',
            name='diagnostico',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Diagnostico'),
        ),
        migrations.AlterField(
            model_name='reembolso',
            name='fecha_siniestro',
            field=models.DateField(blank=True, null=True, verbose_name='fecha de siniestro'),
        ),
        migrations.AlterField(
            model_name='reembolso',
            name='paciente',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Paciente'),
        ),
    ]
