# Generated by Django 5.1.5 on 2025-03-15 15:15

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0008_alter_reembolso_diagnostico_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartaaval',
            name='clinica',
        ),
        migrations.RemoveField(
            model_name='cartaaval',
            name='fecha_registro',
        ),
        migrations.RemoveField(
            model_name='cartaaval',
            name='procedimiento',
        ),
        migrations.AddField(
            model_name='cartaaval',
            name='cedula_paciente',
            field=models.FileField(upload_to='pdfs/reembolso/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartaaval',
            name='concepto',
            field=models.CharField(default="", max_length=255, verbose_name='Concepto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartaaval',
            name='fecha_factura',
            field=models.DateField(default="2025-03-15", verbose_name='Fecha de factura'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cartaaval',
            name='diagnostico',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Diagnostico'),
        ),
        migrations.AlterField(
            model_name='cartaaval',
            name='fecha_siniestro',
            field=models.DateField(blank=True, null=True, verbose_name='fecha de siniestro'),
        ),
        migrations.AlterField(
            model_name='cartaaval',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Numero de factura'),
        ),
        migrations.AlterField(
            model_name='cartaaval',
            name='informe_ampliado',
            field=models.FileField(upload_to='pdfs/reembolso/'),
        ),
        migrations.AlterField(
            model_name='cartaaval',
            name='informe_resultado',
            field=models.FileField(upload_to='pdfs/reembolso/'),
        ),
        migrations.AlterField(
            model_name='cartaaval',
            name='paciente',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Paciente'),
        ),
    ]
