# Generated by Django 5.1.5 on 2025-04-14 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0009_remove_cartaaval_clinica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reembolso',
            name='nroControl',
            field=models.CharField(default=1, max_length=50, verbose_name='Nro de control'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reembolso',
            name='diagnostico',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Diagnóstico'),
        ),
        migrations.AlterField(
            model_name='reembolso',
            name='fecha_siniestro',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de siniestro'),
        ),
        migrations.AlterField(
            model_name='reembolso',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Número de factura'),
        ),
        migrations.AlterField(
            model_name='reembolso',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto'),
        ),
    ]
