# Generated by Django 5.1.5 on 2025-04-14 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0010_reembolso_nrocontrol_alter_reembolso_diagnostico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reembolso',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20),
        ),
    ]
